services:
  proxy:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:8080"
    networks:
      - backend
    pull_policy: always

  user-service:
    image: saphka/location-tracker-user:1.0.0-SNAPSHOT
    environment:
      SPRING_PROFILES_INCLUDE: "dev"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://host.docker.internal:5432/postgres"
      SPRING_R2DBC_URL: "r2dbc:postgresql://host.docker.internal:5432/postgres"
    networks:
      - backend
    pull_policy: always

networks:
  backend: {}