/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "location-tracker"
include(":location-tracker-commons")
include(":location-tracker-user")
include(":location-tracker-location")
