/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "location-tracker-parent"
include(":location-tracker-commons")
include(":location-tracker-user")
