---
# tasks file for db
- name: add postgres repo
  become: yes
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt focal-pgdg main
    update_cache: false
  tags: [ never, setup ]
- name: add postgres repo key
  become: yes
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
  tags: [ never, setup ]
- name: install postgres
  become: yes
  apt:
    name: postgresql-13
    update_cache: yes
  tags: [ never, setup ]