server:
  servlet:
    context-path: /api/v1

spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  autoconfigure:
    exclude: >
      org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,
      org.springframework.boot.autoconfigure.jooq.JooqAutoConfiguration
  datasource:
    hikari:
      maximum-pool-size: 1

jwt:
  issuer: www.locationtracker.org
  lifetime: 15
  keystore: classpath:keystore/token-prod.jks
