all:
  children:
    springbox_location_server_1:
      hosts:
        location_server_1:
          ansible_host: 185.251.89.125
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/ansible
    gateway:
      children:
        springbox_location_server_1: {}
    service:
      children:
        springbox_location_server_1: {}
    db:
      children:
        springbox_location_server_1: {}