---
# tasks file for roles/software
- include_vars: secrets.yml
  tags: always
- name: install openjdk
  become: true
  apt:
    name: openjdk-17-jdk
    update_cache: yes
  tags: [ never, setup ]
- name: create service group
  become: true
  group:
    name: location
  tags: [ never, setup ]
- name: create service user
  become: true
  user:
    name: location
    group: location
  tags: [ never, setup ]
- name: create directory
  become: true
  file:
    path: /etc/sysconfig
    state: directory
- name: copy env file
  become: true
  template:
    src: systemd/location-tracker.j2
    dest: "/etc/sysconfig/location-tracker-{{ service_name }}"
    mode: '600'
    owner: root
  vars:
    service_name: "{{ item.service }}"
    grpc_port: "{{ item.grpc_port }}"
  with_items:
    - service: user
      grpc_port: 6565
    - service: location
      grpc_port: 6575
- name: copy service files
  become: true
  template:
    src: systemd/location-tracker.service.j2
    dest: "/etc/systemd/system/location-tracker-{{ item }}.service"
  vars:
    service_name: "{{ item }}"
  with_items:
    - user
    - location
  notify: restart systemd
- name: copy jar files
  become: true
  copy:
    src: "location-tracker-{{ item }}.jar"
    dest: "/opt/location-tracker/{{ item }}/"
    owner: location
  with_items:
    - user
    - location
  notify: "restart {{ item }}"
- name: enable and start services
  become: true
  service:
    name: "location-tracker-{{ item }}"
    enabled: yes
    state: started
  with_items:
    - user
    - location