---
# tasks file for roles/software
- name: install openjdk
  become: yes
  apt:
    name: openjdk-17-jdk
    update_cache: yes
  tags: [ never, setup ]
- name: create service group
  become: yes
  group:
    name: location
  tags: [ never, setup ]
- name: create service user
  become: yes
  user:
    name: location
    group: location
  tags: [ never, setup ]
- name: copy service files
  become: yes
  copy:
    src: systemd/
    dest: /etc/systemd/system/
  tags: [ never, setup ]
  notify: restart systemd
- name: copy user jar files
  become: yes
  copy:
    src: location-tracker-user.jar
    dest: /opt/location-tracker/user/
    owner: location
  notify: restart user
- name: copy location jar files
  become: yes
  copy:
    src: location-tracker-location.jar
    dest: /opt/location-tracker/location/
    owner: location
  notify: restart user
- name: enable and start user service
  become: yes
  service:
    name: location-tracker-user
    enabled: yes
    state: started
- name: enable and start location service
  become: yes
  service:
    name: location-tracker-location
    enabled: yes
    state: started