spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/location_tracker
    username: postgres
    password: postgres
    hikari:
      schema: location_tracker_user

jwt:
  secret:
    file: /Users/alex/IdeaProjects/location-jwt-secret.txt