/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    id("nu.studer.jooq")
}

abstract class LocationJooqExtension {
    abstract val packageName: Property<String>
    abstract val jooqVersion: Property<String>

    init {
        jooqVersion.set("3.15.4")
    }
}

val locationJooqExtension = extensions.create<LocationJooqExtension>("locationJooq")

afterEvaluate {
    dependencies {
        jooqGenerator("org.jooq:jooq-meta-extensions-liquibase:${locationJooqExtension.jooqVersion.get()}")
        jooqGenerator("org.liquibase:liquibase-core:3.10.3")
        jooqGenerator("org.yaml:snakeyaml:1.28")
        jooqGenerator("org.slf4j:slf4j-jdk14:1.7.30")
    }

    jooq {
        version.set("3.15.4")
        configurations {
            create("main") {
                generateSchemaSourceOnCompilation.set(true)
                jooqConfiguration.apply {
                    generator.apply {
                        name = "org.jooq.codegen.JavaGenerator"
                        target.apply {
                            packageName = locationJooqExtension.packageName.get()
                        }
                        database.apply {
                            name = "org.jooq.meta.extensions.liquibase.LiquibaseDatabase"
                            properties.add(
                                org.jooq.meta.jaxb.Property().withKey("scripts")
                                    .withValue("src/main/resources/db/changelog/db.changelog-master.yml")
                            )
                            properties.add(
                                org.jooq.meta.jaxb.Property().withKey("includeLiquibaseTables").withValue("false")
                            )
                        }
                    }
                }
            }
        }
    }
}