import org.gradle.api.internal.provider.DefaultProperty

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    id("com.palantir.docker")
}

afterEvaluate {
    val bootJarTask = tasks.getByName("bootJar")
    val jarPath: String = (bootJarTask.property("archiveFileName") as DefaultProperty<*>).get() as String


    docker {
        name = "${project.name}:${project.version}"
        files(
            rootProject.file("docker/Dockerfile"),
            bootJarTask.property("outputs")
        )
        buildArgs(
            mapOf("JAR_FILE" to jarPath)
        )
    }
}