import com.google.protobuf.gradle.*
import gradle.kotlin.dsl.accessors._16b8362bcc7ce0ceefeea2f7898dd0fa.ext

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    id("org.saphka.location.java-conventions")
    id("com.google.protobuf")
}

val versions = ext.properties["versions"] as Map<String, String>

protobuf {
    protoc {
        artifact = "com.google.protobuf:protoc:${versions["protoc"]}"
    }
    plugins {
        id("grpc") {
            artifact = "io.grpc:protoc-gen-grpc-java:${versions["grpc"]}"
        }
    }
    generateProtoTasks {
        all().forEach {
            it.plugins {
                id("grpc")
            }
        }
    }
}
