/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    id("org.saphka.location.java-conventions")
    id("nu.studer.jooq")
}

val versions = ext.properties["versions"] as Map<String, String>

abstract class LocationJooqExtension {
    abstract val packageName: Property<String>
}

val locationJooqExtension = extensions.create<LocationJooqExtension>("locationJooq")

afterEvaluate {
    dependencies {
        jooqGenerator("org.jooq:jooq-meta-extensions-liquibase:${versions["jooq"]}")
        jooqGenerator("org.liquibase:liquibase-core:${versions["liquibase-core"]}")
        jooqGenerator("org.yaml:snakeyaml:${versions["snakeyaml"]}")
        jooqGenerator("org.slf4j:slf4j-jdk14:${versions["slf4j"]}")
    }

    jooq {
        version.set(versions["jooq"])
        configurations {
            create("main") {
                generateSchemaSourceOnCompilation.set(true)
                jooqConfiguration.apply {
                    generator.apply {
                        name = "org.jooq.codegen.JavaGenerator"
                        target.apply {
                            packageName = locationJooqExtension.packageName.get()
                        }
                        database.apply {
                            name = "org.jooq.meta.extensions.liquibase.LiquibaseDatabase"
                            properties.add(
                                org.jooq.meta.jaxb.Property().withKey("scripts")
                                    .withValue("src/main/resources/db/changelog/db.changelog-master.yml")
                            )
                            properties.add(
                                org.jooq.meta.jaxb.Property().withKey("includeLiquibaseTables").withValue("false")
                            )
                        }
                    }
                }
            }
        }
    }
}