---
# tasks file for roles/nginx
- name: install nginx
  become: yes
  apt:
    name: nginx
    update_cache: yes
- name: copy config
  become: yes
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
- name: enable and start service
  become: yes
  service:
    name: nginx
    enabled: yes
    state: started