---
# tasks file for roles/nginx
- name: install nginx
  become: true
  apt:
    name: nginx
    update_cache: yes
  tags: [ never, setup ]
- name: copy config
  become: true
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
- name: enable and start service
  become: true
  service:
    name: nginx
    enabled: yes
    state: started