/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.saphka.location.java-conventions")
}

dependencies {
    implementation(libs.kotlin.lib)
    implementation(libs.kotlin.reflect)
    implementation(libs.jjwt.api)
    implementation(libs.jjwt.impl)
    implementation(libs.jjwt.jackson)
    implementation(libs.spring.boot.starter)
    implementation(libs.spring.security.config)
    implementation(libs.spring.security.oauth2.res)
    implementation(libs.spring.security.oauth2.jose)
    implementation(libs.reactor.core)
    implementation(libs.grpc.stub)
    implementation(libs.jooq)
    implementation(libs.hikari)
    implementation(libs.spring.boot.starter.test)
    implementation(libs.test.containers.postgresql)
}

description = "location-tracker-commons"
