/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.32")
    implementation("org.jetbrains.kotlin:kotlin-allopen:1.5.32")
    implementation("nu.studer:gradle-jooq-plugin:6.0.1")
    implementation("gradle.plugin.com.google.protobuf:protobuf-gradle-plugin:0.8.18")
    implementation("com.palantir.gradle.docker:gradle-docker:0.31.0")
}