/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.saphka.location.java-conventions")
}

dependencies {
    implementation(project(":location-tracker-commons"))
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31")
    implementation("org.jetbrains.kotlin:kotlin-reflect:1.5.31")
    implementation("org.springframework.boot:spring-boot-starter-jdbc:2.5.6")
    implementation("io.github.lognet:grpc-spring-boot-starter:4.5.9")
    implementation("org.liquibase:liquibase-core:4.3.5")
    runtimeOnly("org.postgresql:postgresql:42.2.24")
    runtimeOnly("io.r2dbc:r2dbc-postgresql:0.8.10.RELEASE")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.5.6")
    testImplementation("io.github.lognet:grpc-client-spring-boot-starter:4.5.9")
}

description = "location-tracker-user"
