name: Test Pull Request
on: [pull_request]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew test