name: Deploy Containers
on:
  release:
    types:
      - created
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew build -Papplication.version=${GITHUB_REF##*/}