name: Deploy Containers
on:
  release:
    types:
      - created
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
      - uses: gradle/gradle-build-action@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_AUTH_TOKEN }}
      - run: VERSION_TAG=${GITHUB_REF##*/}
      - run: ./gradlew docker dockerPushDockerHub -Papplication.version=$VERSION_TAG