name: Deploy Containers
on:
  release:
    types:
      - created
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: zulu
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew build -Papplication.version=${GITHUB_REF##*/}
      - uses: actions/upload-artifact@v2
        with:
          name: location-tracker-location.jar
          path: location-tracker-location/build/libs/location-tracker-location.jar
      - uses: actions/upload-artifact@v2
        with:
          name: location-tracker-user.jar
          path: location-tracker-user/build/libs/location-tracker-user.jar
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install ansible==2.12.1
      - name: set ansible config secrets
        env:
          ANSIBLE_SSH_KEY: ${{ secrets.ANSIBLE_SSH_KEY }}
          ANSIBLE_VAULT_KEY: ${{ secrets.ANSIBLE_VAULT_KEY }}
        run: |
          mkdir .ssh
          echo "$ANSIBLE_SSH_KEY" > .ssh/ansible
          chmod 600 .ssh/ansible
          echo "$ANSIBLE_VAULT_KEY" > .ansible_vault_key
          chmod 600 .ansible_vault_key
      - uses: actions/download-artifact@v2
        with:
          name: location-tracker-location.jar
          path: ansible/roles/service/files/
      - uses: actions/download-artifact@v2
        with:
          name: location-tracker-user.jar
          path: ansible/roles/service/files/
      - run: ansible-playbook ansible/setup_server.yml -i ansible/inventory/sprintbox.yml --vault-password-file .ansible_vault_key
      - run: ansible-playbook ansible/setup_gateway.yml -i ansible/inventory/sprintbox.yml --vault-password-file .ansible_vault_key
